config/routes.rb
Rails.application.routes.draw do
  resources :human_resources
  devise_for :project_managers
  resources :cost_payment_plans
  resources :projects do
    resources :milestones do
      resources :tasks do
        member do
          post 'estimate_duration'
        end
      end
    end
    resources :stakeholders do
      member do
        put 'increase_commitment'
      end
    end
    member do
      post 'create_requirement' # create_requirement_project_path (projects#create_requirement)
      post 'configure_simulator' 
      put 'edit_budget'  # /projects/:id/edit_budget
      get 'execute_step'
      post 'negotiate'
    end
  end

    get 'projects/:id/costs', to: 'projects#costs', as: 'project_costs'
    get 'projects/:project_id/milestones/:milestone_id/tasks/:task_id/add_cost_line', to: 'tasks#add_cost_line', as: 'new_task_cost'
    post 'projects/:project_id/milestones/:milestone_id/tasks/:task_id/add_cost_line', to: 'tasks#create_cost_line', as: 'task_cost'
    get 'projects/:project_id/pay_cost/:cost_line_id', to: 'projects#insert_real_cost', as: 'set_real_cost'
    post 'projects/:project_id/pay_cost/:cost_line_id', to: 'projects#save_real_cost', as: 'pay_cost'

    post 'projects/:id/clone', to: 'projects#clone', as: 'clone_project'
    post 'projects/:project_id/milestones/clone', to: 'milestones#clone', as: 'clone_milestones'
    post 'projects/:project_id/milestones/:id/tasks/clone', to: 'tasks#clone', as: 'clone_tasks'

    get 'projects/:project_id/precedents', to: 'milestones#precedent_index', as: 'precedents'
    post 'projects/:project_id/precedents', to: 'milestones#create_precedent', as: 'create_precedents'
    get 'projects/:project_id/precedents/new', to: 'milestones#new_precedent', as: 'new_precedents'
    
    get '/', to: 'projects#scope_statement', as: 'scope_statement'

    get 'human_resources_shop', to: 'human_resources#shop', as: 'human_resources_shop'
    post 'human_resources/:id/clone', to: 'human_resources#clone', as: 'human_resources_clone'

    post 'projects/:project_id/milestones/:milestone_id/tasks/:id/assign_resource', to: 'tasks#assign_resource', as: 'assign_resource'

    put 'projects/:project_id/edit_requirement/:id', to: 'projects#edit_requirement', as: 'edit_requirement'

  root 'projects#scope_statement'

end

app/models/milestone.rb
# == Schema Information
#
# Table name: milestones
#
#  id                 :integer          not null, primary key
#  name               :string
#  description        :text
#  due_date           :date
#  created_at         :datetime         not null
#  updated_at         :datetime         not null
#  project_id         :integer
#  is_admin_milestone :boolean
#  fake               :boolean
#  status             :string
#

class Milestone < ActiveRecord::Base
  has_many :tasks, dependent: :destroy
  belongs_to :project

  scope :from_admin, -> { where(is_admin_milestone: true) }
  scope :no_fake,  -> { where(fake: false) }
  scope :not_aproved, -> { where("milestones.status != 'Aprobado' OR milestones.status IS NULL ") }
  scope :aproved, -> { where(status: 'Aprobado') }

  # Method for assigning a milestone to the task
  def add_task(task)
    task.milestone_id = id
    task.save
  end

  def ready?
    tasks.each do |task|
      p task.status
      return false if task.status != 'Terminada'
    end
    true
  end

  def restart
    tasks.map { |task| task.restart }
    update(status: 'No aprobado')
  end

end

app/models/project.rb
# == Schema Information
#
# Table name: projects
#
#  id                  :integer          not null, primary key
#  name                :string
#  actual_week         :integer
#  created_at          :datetime         not null
#  updated_at          :datetime         not null
#  project_manager_id  :integer
#  status              :string
#  is_admin_project    :boolean
#  start_date          :date
#  strategic_objective :text
#

class Project < ActiveRecord::Base
  has_many :milestones, dependent: :destroy
  has_one :cost_payment_plan, dependent: :destroy
  has_many :stakeholders, dependent: :destroy
  has_one :budget, dependent: :destroy
  has_many :requirements, dependent: :destroy
  has_many :human_resources, dependent: :destroy
  has_one :simulator, dependent: :destroy

  scope :from_admin, -> { where(is_admin_project: true) }
  scope :cloned, -> { where(is_admin_project: false) }

  def modificable?
    return true if (status == 'Inicio')
    false
  end

  def monitorable?
    return true if (status == 'Monitoreo y control')
    false
  end

  def human_resources_for_select
    human_resources.map { |hr| [hr.description, hr.id] }
  end

  # This method returns the duration of the project in days
  def duration
    e_date = start_date
    all_tasks.each do |task|
      e_date = task.end_date if task.end_date > e_date
    end
    (e_date - start_date).to_i
  end

  # This method cares of paying the salaries, it verifies that it hasn't
  # been paid earlier this week.
  # It's funded by the activities reserve
  def pay_salaries(week)
    cpp = cost_payment_plan
    human_resources.each do |hr|
      nyd = 'Pago sueldo ' + hr.name
      am = hr.salary
      unless CostLine.where(name: nyd, payment_week: week).length > 0
        cl = CostLine.new(name: nyd, description: nyd,
                          amount: am, real_amount: am,
                          payment_week: week, real_payment_week: week,
                          cost_payment_plan_id: cpp.id, status: 'Pagado',
                          funding_source: 'Reserva de actividades')
        cl.save
        use_budget(cl)
      end
    end
  end

  # Method used to increase the used amount of the budget
  def use_budget(cost_line)
    bud = budget
    case cost_line.funding_source
    when 'Costo de actividades'
      bud.activities_cost_used += cost_line.real_amount
    when 'Reserva de actividades'
      bud.activities_reserve_used += cost_line.real_amount
    when 'Reserva de contingencias'
      bud.contingency_reserve_used += cost_line.real_amount
    when 'Reserva de gestión'
      bud.managment_reserve_used += cost_line.real_amount
    end
    bud.save 
  end

  # This method return an array of the project tasks with columns
  # [:name, :start_date, :end_date]
  def tasks_for_timeline
    tasks_f_time ||= []
    milestones.each do |mile|
      mile.tasks.each do |task|
        task.update(start_date: start_date) if task.start_date.nil?
        task.update(end_date: task.start_date + task.pm_duration_estimation.days) if task.end_date.nil?
        tasks_f_time << [task.name + ' | ' + mile.name + ' | ' + task.advance_percentage.to_s + "% ", task.start_date, task.end_date]
      end
    end
    tasks_f_time
  end

  def all_tasks
    tasks ||= []
    milestones.each do |mile|
      mile.tasks.each do |task|
        tasks << task
      end
    end
    tasks
  end

  def active_tasks
    tasks ||= []
    milestones.each do |mile|
      mile.tasks.active.each do |task|
        tasks << task
      end
    end
    tasks
  end

  def waiting_tasks
    tasks ||= []
    milestones.each do |mile|
      mile.tasks.waiting.each do |task|
        tasks << task
      end
    end
    tasks
  end

  def finished_tasks
    tasks ||= []
    milestones.each do |mile|
      mile.tasks.finished.each do |task|
        tasks << task
      end
    end
    tasks
  end

  # Clone all the elements and params of the original project to
  # the new one
  def clone_characteristics_from(original_project, current_project_manager)
    # Create a new cost payment plan for this project
    cpp = CostPaymentPlan.create!
    self.cost_payment_plan = cpp
    clone_budget_from(original_project)
    clone_requirements_from(original_project)
    clone_stakeholders_from(original_project)
    self.simulator = original_project.simulator.clone
    self.project_manager_id = current_project_manager.id
    self.is_admin_project = current_project_manager.has_role? :admin
    self.status = 'Inicio'
    save
  end

  def clone_budget_from(original_project)
    self.budget = original_project.budget.dup
    save
  end

  # Clone the requirements of the project
  def clone_requirements_from(original_project)
    original_project.requirements.each do |req|
      r2 = req.dup
      r2.attributes = { project_id: id }
      r2.save
    end
  end

  # Clone the stakeholders
  def clone_stakeholders_from(original_project)
    original_project.stakeholders.each do |stakeholder|
      sh2 = stakeholder.dup
      sh2.attributes =  { project_id: id, is_admin_stakeholder: false }
      sh2.save
    end
  end

  # ---- Methods for simulation ---- #

  # To win the game the project must be completed,
  # in order to do that all the milestones should be finished
  def win?
    milestones.each do |mile|
      return false unless mile.status == 'Aprobado'
    end
    true
  end

  # To loose the game 1 of 3 conditions mus occur:
  # => Project expenses consume the profit of the project
  # => Cost for the client increases in 25%
  # => There is a delay of more than 25%
  def loose?
    return true if budget.actual_earnings < 0
    return true if simulator.initial_budget and budget.total_used > 1.25 * simulator.initial_budget
    return true if simulator.actual_duration and simulator.actual_duration > 1.25 * simulator.original_duration
    return true if simulator.day and simulator.day > simulator.actual_duration
    false
  end

  # This method is for restarting thr project
  def restart
    budget.restart
    cost_payment_plan.restart
    self.update(actual_week: 0, status: 'Inicio')
    milestones.map { |mile| mile.restart }
  end
end

app/controllers/milestones_controller.rb
class MilestonesController < ApplicationController
  before_action :set_milestone, only: [:show, :edit, :update, :destroy]
  before_action :set_project, :set_admin
  before_action :authenticate_project_manager!
  # GET /milestones
  # GET /milestones.json
  def index
    @milestones = @project.milestones
    parent_project = Project.from_admin.where(name: @project.name).first
    @posible_milestones = parent_project.milestones.to_a.keep_if { |mile| @milestones.where(name: mile.name).length == 0 }
  end

  # GET /milestones/1
  # GET /milestones/1.json
  def show
    @tasks = @milestone.tasks
    source_milestone = Milestone.from_admin.where(name: @milestone.name).first
    @posible_tasks = source_milestone.tasks.to_a.keep_if { |task| @tasks.where(name: task.name).length == 0 }
  end

  # Clone milestones
  def clone
    ids = params[:milestone_ids]
    ids.each do |id|
      milestone = Milestone.find(id).dup
      milestone.project_id = params[:project_id]
      milestone.is_admin_milestone = @admin
      milestone.save
    end
    respond_to do |format|
      format.html {redirect_to project_milestones_path(@project), notice: 'Hito agregado correctamente'}
    end
  end

  # GET /milestones/new
  def new
    @milestone = Milestone.new
  end

  # GET /milestones/1/edit
  def edit
  end

  # POST /milestones
  # POST /milestones.json
  def create
    @milestone = Milestone.new(milestone_params)
    @milestone.project_id = params[:project_id]
    @milestone.is_admin_milestone = @admin
    respond_to do |format|
      if @milestone.save
        format.html { redirect_to project_milestones_path, notice: 'Milestone was successfully created.' }
        format.json { render :show, status: :created, location: @milestone }
      else
        format.html { render :new }
        format.json { render json: @milestone.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /milestones/1
  # PATCH/PUT /milestones/1.json
  def update
    respond_to do |format|
      if @milestone.update(milestone_params)
        format.html { redirect_to project_milestones_path, notice: 'Milestone was successfully updated.' }
        format.json { render :show, status: :ok, location: @milestone }
      else
        format.html { render :edit }
        format.json { render json: @milestone.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /milestones/1
  # DELETE /milestones/1.json
  def destroy
    @milestone.destroy
    respond_to do |format|
      format.html { redirect_to project_milestones_url, notice: 'Milestone was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  #### ----------- Precedent methods --------- ####
  
  # GET projects/1/precedents
  def precedent_index
    @tasks ||= []
    @project.milestones.each do |miles|
      miles.tasks.each do |task|
        task.update(start_date: @project.start_date) if task.start_date.nil?
        task.update(end_date: task.start_date + task.pm_duration_estimation.days) if task.end_date.nil?
        @tasks << task
      end
    end
    @precedents = Precedent.where(project_id: @project.id)
  end

  # GET projects/1/precedents/new
  def new_precedent
    @tasks ||= []
    @project.milestones.each do |miles|
      miles.tasks.each do |task|
        @tasks << task
      end
    end
  end

  # POST projects/1/precedents
  def create_precedent
    p params[:predecessor_id]
    predecessor = params[:predecessor_id].first
    dependent_ids = params[:dependent_ids]
    dependent_ids.each do |dependent|
      precedent = Precedent.new(predecessor_id: predecessor, dependent_id: dependent, project_id: @project.id)
      precedent.save
    end
    respond_to do |format|
        format.html { redirect_to precedents_path(@project, @milestone, @task), notice: 'Dependencia creada corretamente' }
        format.json { render :show, status: :created, location: @cost_line }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_milestone
      @milestone = Milestone.find(params[:id])
    end

    def set_project
      @project = Project.find(params[:project_id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def milestone_params
      params.require(:milestone).permit(:name, :description, :due_date, :fake)
    end

    def set_admin
      @admin = current_project_manager.has_role? :admin
    end
end

app/helpers/milestones_helper.rb
module MilestonesHelper
end

app/views/milestones/_add_milestones_list.html.erb
<% milestones = locals[:milestones]%>
<br>
<h3> Agregar hitos </h3>
<br>
<p> Aquí puedes seleccionar los hitos que quieras agregar a tu proyecto, debes agregar sólo los hitos que encuentres necesarios para el éxito del proyecto.</p>
<%= form_tag clone_milestones_path do %>
<table>
  <thead>
    <tr>
      <th>Nombre</th>
      <th>Descripción</th>
      <th>Fecha de término</th>
      <th colspan="3"> Agregar hito? </th>
    </tr>
  </thead>

  <tbody>
    <% milestones.each do |milestone| %>
      <tr>
        <td><%= milestone.name %></td>
        <td><%= milestone.description %></td>
        <td><%= milestone.due_date %></td>
        <td>
          <%= check_box_tag "milestone_ids[]", milestone.id %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= submit_tag "Agregar", class: "button tiny success" %>
<% end -%>

app/views/milestones/_form.html.erb
<% milestone = locals[:milestone]%>
<% project = locals[:project]%>
<% f = locals[:form]%>
  <% if milestone.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(milestone.errors.count, "error") %> prohibited this milestone from being saved:</h2>

      <ul>
      <% milestone.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :due_date %><br>
    <%= f.date_select :due_date %>
  </div>
  <div class="field">
    <%= f.label :fake %><br>
    <%= f.check_box :fake %>
  </div>
  <div class="actions">
    <%= f.submit(class: 'button success small inline') %>
  </div>

app/views/milestones/_milestones_list.html.erb
<% milestones = locals[:milestones]%>
<p>
  <h1>Listado de hitos</h1>
</p>

<table>
  <thead>
    <tr>
      <th>Nombre</th>
      <th>Descripción</th>
      <th>Fecha de término</th>
      <th colspan="3"> Acciones </th>
    </tr>
  </thead>

  <tbody>
    <% milestones.each do |milestone| %>
      <tr>
        <td><%= milestone.name %></td>
        <td><%= milestone.description %></td>
        <td><%= milestone.due_date %></td>
        <td>
          <ul class='button-group radius'>
            <li><%= link_to 'Ver detalles', project_milestone_path({ :project_id => @project.id, :id => milestone.id}), { class: 'button info tiny' }%></li>
            <li><%= link_to 'Editar', edit_project_milestone_path({ :id => milestone.id, :project_id => @project.id}), { class: 'button secondary tiny' } if @admin%></li>
            <li><%= link_to 'Eliminar', project_milestone_path({ :id => milestone.id, :project_id => @project.id}), class: 'button secondary tiny' , method: :delete, data: { confirm: 'Are you sure?' }%></li>
          </ul>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/milestones/edit.html.erb
<h1>Editing Milestone</h1>

<%= form_for(@milestone, url: project_milestone_path(@project, @milestone)) do |f| %>
	<%= render 'form', :locals => {form: f, milestone: @milestone, project: @project}%>
<% end %>
<%= link_to 'Show', project_milestone_path({:project_id => params[:project_id], :id => params[:id]}) %> |
<%= link_to 'Back', project_milestones_path %>

app/views/milestones/index.html.erb
<div class="row">
  <p></p>
 <%= link_to 'Volver a proyecto', project_path(@project), class: 'button tiny secondary' %>
 <%= link_to 'Ver precedencias de tareas', precedents_path, class: 'button tiny info' %>
</div>
<%- if @milestones.length > 0 %>
  <%= render 'milestones_list', locals: { milestones: @milestones } %>
<% end -%>
<br>
<%- if @project.modificable? and not(@admin)%>
  <%= render 'add_milestones_list', locals: { milestones: @posible_milestones } %>
<% end -%>
<br>
<%- if @admin %>
  <%= link_to 'Agregar hito nuevo', new_project_milestone_path, class: 'button tiny info' %>
<% end -%>

app/views/milestones/new.html.erb
<h1>New Milestone</h1>

<%= form_for(@milestone, url: project_milestones_path(@project)) do |f| %>
	<%= render 'form', :locals => { form: f, milestone: @milestone, project: @project } %>
<%= link_to 'Back', project_milestones_path, { class: 'button warning small' } %>
<% end %>

app/views/milestones/new_precedent.html.erb
<p>
  <h3>Agregar nuevas precedencias</h3>
</p>
<p>
  Para agregar nuevas dependencias seleccione la tarea precedente de la columna izquierda y todas las tareas que dependan de esta (puede seleccionar más de una) en la columna de la izquierda. 
</p>
<%= form_tag create_precedents_path(@project), method: :post %>
<div class="left large-6">
  <table>
    <thead>
      <th>Tarea predecesora</th>
      <th>Sel. 1</th>
    </thead>
    <tbody>
      <% @tasks.each do |task| %>
        <tr>
          <td><%= task.name + ' | ' + task.milestone.name %></td>
          <td><%= check_box_tag "predecessor_id[]", task.id %></td>
        </tr>
      <% end -%>
    </tbody>
  </table>
</div>
<div class="left large-6">
  <table>
    <thead>
      <th>Sel. (1 o más)</th>
      <th>Tarea dependiente</th>
    </thead>
    <tbody>
      <% @tasks.each do |task| %>
        <tr>
          <td><%= check_box_tag "dependent_ids[]", task.id %></td>
          <td><%= task.name + ' | ' + task.milestone.name %></td>
        </tr>
      <% end -%>
    </tbody>
  </table>
</div>
<%= submit_tag "Agregar", class: "button tiny success" %>
  <%= link_to 'Atrás', precedents_path(@project), class: 'button secondary tiny' %>

app/views/milestones/precedent_index.html.erb
<p>
	<h3>Lista de precedencias</h3>
</p>

<table>
	<thead>
		<th>Tarea predecesora</th>
		<th>Tarea dependiente</th>
	</thead>
	<tbody>
		<% @precedents.each do |precedent| %>
		<tr>
			<td><%= @tasks.find { |task| task.id == precedent.predecessor_id }.name %> </td>
			<td>
				<%= @tasks.find { |task| task.id == precedent.dependent_id }.name %>
				
			</td>
		</tr>
		<% end -%>
	</tbody>
</table>

<p>
	<%= link_to 'Agregar nueva dependencia', new_precedents_path, class: 'button success tiny' %>
	<%= link_to 'Atrás', project_milestones_path(@project), class: 'button secondary tiny' %>
</p>

app/views/milestones/show.html.erb
<div class="row">
  <p></p>
  <%= link_to 'Volver a listado de hitos', project_milestones_path(@project), class: 'button secondary tiny' %>
</div>
<p>
  <h2><%= @milestone.name.camelize %></h2>
  <strong> Fecha término: <%= @milestone.due_date %> </strong>
</p>
<p>
  <h6> <%= @milestone.description.camelize %></h4>
</p>

<p>
  <h4>Lista de actividades para lograrlo</h4>
  <%= render 'tasks/task_list', :locals => {tasks: @tasks} %>
</p>

<% unless @admin %>
<p>
  <h4>Agregar actividades</h4>
  <%= form_tag clone_tasks_url(:project_id => @project.id, :milestone_id => @milestone.id) do %>
  <%= render 'tasks/add_tasks_list', locals: { tasks: @posible_tasks } %>
  <% end -%>
</p>
<% else %>
  <%= link_to 'Crear nueva actividad', new_project_milestone_task_path(@project, @milestone), { class: 'button success tiny' } %> 
  <%= link_to 'Edit', edit_project_milestone_path(@project, @milestone) %> |
  <%= link_to 'Back', project_milestones_path(@project) %>
<% end -%>