config/routes.rb
Rails.application.routes.draw do
  resources :human_resources
  devise_for :project_managers
  resources :cost_payment_plans
  resources :projects do
    resources :milestones do
      resources :tasks do
        member do
          post 'estimate_duration'
        end
      end
    end
    resources :stakeholders do
      member do
        put 'increase_commitment'
      end
    end
    member do
      post 'create_requirement' # create_requirement_project_path (projects#create_requirement)
      post 'configure_simulator' 
      put 'edit_budget'  # /projects/:id/edit_budget
      get 'execute_step'
      post 'negotiate'
    end
  end

    get 'projects/:id/costs', to: 'projects#costs', as: 'project_costs'
    get 'projects/:project_id/milestones/:milestone_id/tasks/:task_id/add_cost_line', to: 'tasks#add_cost_line', as: 'new_task_cost'
    post 'projects/:project_id/milestones/:milestone_id/tasks/:task_id/add_cost_line', to: 'tasks#create_cost_line', as: 'task_cost'
    get 'projects/:project_id/pay_cost/:cost_line_id', to: 'projects#insert_real_cost', as: 'set_real_cost'
    post 'projects/:project_id/pay_cost/:cost_line_id', to: 'projects#save_real_cost', as: 'pay_cost'

    post 'projects/:id/clone', to: 'projects#clone', as: 'clone_project'
    post 'projects/:project_id/milestones/clone', to: 'milestones#clone', as: 'clone_milestones'
    post 'projects/:project_id/milestones/:id/tasks/clone', to: 'tasks#clone', as: 'clone_tasks'

    get 'projects/:project_id/precedents', to: 'milestones#precedent_index', as: 'precedents'
    post 'projects/:project_id/precedents', to: 'milestones#create_precedent', as: 'create_precedents'
    get 'projects/:project_id/precedents/new', to: 'milestones#new_precedent', as: 'new_precedents'
    
    get '/', to: 'projects#scope_statement', as: 'scope_statement'

    get 'human_resources_shop', to: 'human_resources#shop', as: 'human_resources_shop'
    post 'human_resources/:id/clone', to: 'human_resources#clone', as: 'human_resources_clone'

    post 'projects/:project_id/milestones/:milestone_id/tasks/:id/assign_resource', to: 'tasks#assign_resource', as: 'assign_resource'

    put 'projects/:project_id/edit_requirement/:id', to: 'projects#edit_requirement', as: 'edit_requirement'

  root 'projects#scope_statement'

end

app/models/milestone.rb
# == Schema Information
#
# Table name: milestones
#
#  id                 :integer          not null, primary key
#  name               :string
#  description        :text
#  due_date           :date
#  created_at         :datetime         not null
#  updated_at         :datetime         not null
#  project_id         :integer
#  is_admin_milestone :boolean
#  fake               :boolean
#  status             :string
#

class Milestone < ActiveRecord::Base
  has_many :tasks, dependent: :destroy
  belongs_to :project

  scope :from_admin, -> { where(is_admin_milestone: true) }
  scope :no_fake,  -> { where(fake: false) }
  scope :not_aproved, -> { where("milestones.status != 'Aprobado' OR milestones.status IS NULL ") }
  scope :aproved, -> { where(status: 'Aprobado') }

  # Method for assigning a milestone to the task
  def add_task(task)
    task.milestone_id = id
    task.save
  end

  def ready?
    tasks.each do |task|
      p task.status
      return false if task.status != 'Terminada'
    end
    true
  end

  def restart
    tasks.map { |task| task.restart }
    update(status: 'No aprobado')
  end

end

app/models/task.rb
# == Schema Information
#
# Table name: tasks
#
#  id                        :integer          not null, primary key
#  name                      :string
#  description               :text
#  min_duration              :integer
#  most_probable_duration    :integer
#  max_duration              :integer
#  pm_duration_estimation    :integer
#  created_at                :datetime         not null
#  updated_at                :datetime         not null
#  milestone_id              :integer
#  is_admin_task             :boolean
#  fake                      :boolean
#  admin_duration_estimation :integer
#  advance_percentage        :integer
#  status                    :string
#  start_date                :date
#  end_date                  :date
#

class Task < ActiveRecord::Base
  resourcify
  belongs_to :milestone
  has_many :cost_lines
  has_many :resource_assignations, dependent: :destroy
  has_many :human_resources, through: :resource_assignations

  default_scope { order(start_date: :asc, name: :asc) }
  scope :admin, -> { where(is_admin_task: true) }
  scope :no_fake, -> { where(fake: false) }

  scope :start_today, ->(actual_date) { where(start_date: actual_date) }

  scope :waiting, -> { where(status: 'Pendiente') }
  scope :active, -> { where(status: 'En proceso') }
  scope :finished, -> { where(status: 'Terminada') }
  scope :unfinished, -> { where.not(status: 'Terminada') }
  
  def add_milestone(milestone)
    self.milestone_id = milestone.id
    save
  end

  def restart
    update(advance_percentage: 0, status: 'Pendiente', start_date: nil, end_date: nil)
  end
  # Vemos si ya se estimo la duracion de la tarea
  def estimated?
    return false if pm_duration_estimation.nil?
    true
  end

  # Defines the advance of a task to acomplish 100%
  def daily_advance
    actual_duration = (end_date - start_date).to_i
    return 1.0 / admin_duration_estimation if actual_duration < admin_duration_estimation
    1.0 / actual_duration
  end

  def advance(days)
    self.advance_percentage ||= 0
    if human_resources.available.length > 0
      self.advance_percentage += (daily_advance * days * 100).ceil
      self.status = 'En proceso' if self.advance_percentage > 0
      self.status = 'Terminada' if self.advance_percentage >= 100
      save
    else
      self.update_end_date(1)
      self.advance_percentage += (daily_advance * days * 100).ceil
      self.status = 'En proceso' if self.advance_percentage > 0
      self.status = 'Terminada' if self.advance_percentage >= 100
      save
    end
  end

  def clone_costs(other_task_id, cpp_id)
    cost_lines.each do |cost_line|
      cl = cost_line.dup
      cl.task_id = other_task_id
      cl.cost_payment_plan_id = cpp_id
      cl.save
    end
  end

  ##########################################
  #### --- Advance and delay tasks --- #####
  ##########################################
  def delay_start(s_date)
    return false if start_date >= s_date
    self.start_date = s_date
    save
  end

  def delay_end(e_date)
    return false if end_date >= e_date
    self.end_date = e_date
    save
  end

  def advance_start(s_date)
    return false if start_date <= s_date
    self.start_date = s_date
    save
  end

  def advance_end(e_date)
    return false if end_date <= e_date
    self.end_date = e_date
    save
  end

  ############################################
  #### --- Advance and delays control --- ####
  ############################################

  # This method is used when a new precedent relation is created or a task 
  # with dependents is delayed
  def update_start_date(s_date)
    if delay_start(s_date)
      if delay_end(start_date + pm_duration_estimation)
        dependent_tasks_id = Precedent.where(predecessor_id: id).pluck(:dependent_id)
        dependent_tasks_id.each do |t_id|
          Task.find(t_id).update_start_date(end_date)
        end
      end
    end
  end

  # This method is used when the simulation determines that the task 
  # ends later than it was supposed 
  # @ds : days of delay, if negative => advance (not implemented yet)
  def update_end_date(ds)
    actual_duration = (self.end_date - self.start_date).to_i
    days_worked = self.advance_percentage / 100.0 * (actual_duration) 
    if delay_end(end_date + ds.days)
      self.update(advance_percentage: (days_worked / (actual_duration + ds) * 100).to_i)
      dependent_tasks_id = Precedent.where(predecessor_id: id).pluck(:dependent_id)
      dependent_tasks_id.each do |t_id|
        Task.find(t_id).update_start_date(end_date)
      end
    # else 
    #   if advance(end_date + ds.days)
    #     dependent_tasks_id = Precedent.select(:dependent_id).where(predecessor_id: id)
    #     dependent_tasks_id.each do |t_id|
    #       t = Task.find(t_id)
    #     end
    #   end
    end
  end

  def latest_end_date(task_ids_precedent)
    # e_date = self.milestone.project.start_date
    task_ids_precedent.reduce(pjct_start_date) { |e_date, task_id| Task.find(task_id).end_date}
    task_ids_precedent.each do |task_id|
      task = Task.find(task_id)
      e_date = task.end_date unless task.end_date < e_date and task.end_date.nil?
    end
  end

  def pjct_start_date
    milestone.project.start_date
  end

  def simulation_date
    pjct_start_date + milestone.project.simulator.day.days
  end

end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: [:show, :edit, :update, :destroy, :estimate_duration, :assign_resource]
  before_action :set_project, :set_admin
  before_action :set_milestone, except: [:clone]
  before_action :authenticate_project_manager!
  # GET /tasks
  # GET /tasks.json
  def index
    @tasks = @milestone.tasks
  end


  # GET /tasks/1
  # GET /tasks/1.json
  def show
    @costs_list = @task.cost_lines
    @hhrr_array = @project.human_resources_for_select
    @hhrr_assigned = ResourceAssignation.where(task_id: params[:id])
  end

  # GET /tasks/new
  def new
    @task = Task.new
    # Under which milestone the activity would take place
    miles = [["", 0]]
    Milestone.pluck(:name, :id).each do |milestone|
      miles << milestone
    end
    @milestones = miles
  end

  # GET /tasks/1/edit
  def edit
  end

  # POST /tasks/1/estimate_duration
  def estimate_duration
    @task.pm_duration_estimation = params[:pm_duration_estimation]
    respond_to do |format|
      if @task.save
        format.html { redirect_to project_milestone_path(@project, @milestone), notice: 'Duración estimada correctamente' }
        format.json { render :show, status: :ok, location: @task }
      else
        format.html { render project_milestone_path(@project, @milestone) }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # Allows a project manager to add tasks from a milestone
  def clone
    @milestone = Milestone.find(params[:id])
    ids = params[:task_ids]
    ids.each do |id|
      original_task = Task.find(id)
      task = original_task.dup
      task.milestone_id = params[:id]
      task.is_admin_task = @admin
      task.status = 'Pendiente'
      task.save
      original_task.clone_costs(task.id, @project.cost_payment_plan.id)
    end
    respond_to do |format|
      format.html { redirect_to project_milestone_path(@project, @milestone), notice: 'Tareas agregadas correctamente' }
    end
  end

  # POST /tasks
  # POST /tasks.json
  def create
    @task = Task.new(task_params)
    @task.milestone_id = params[:milestone_id]
    @task.is_admin_task = @admin
    @task.status = 'Pendiente'
    @task.advance_percentage = 0
    respond_to do |format|
      if @task.save
        format.html { redirect_to project_milestone_path(@project, @milestone), notice: 'Task was successfully created.' }
        format.json { render :show, status: :created, location: @task }
      else
        format.html { render :new }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tasks/1
  # PATCH/PUT /tasks/1.json
  def update
    respond_to do |format|
      if @task.update(task_params)
        format.html { redirect_to project_milestone_path(@project, @milestone), notice: 'Task was successfully updated.' }
        format.json { render :show, status: :ok, location: @task }
      else
        format.html { render :edit }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tasks/1
  # DELETE /tasks/1.json
  def destroy
    @task.destroy
    respond_to do |format|
      format.html { redirect_to project_milestone_path(@project, @milestone), notice: 'Task was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  #### ----------- Cost lines methods ----------- ####

  # GET /tasks/1/add_cost_line
  def add_cost_line
    @task = Task.find(params[:task_id])
    @cost_line = CostLine.new
  end

  # POST 
  def create_cost_line
    @task = Task.find(params[:task_id])
    @cost_line = CostLine.new(cost_line_params)
    @cost_line.task_id = params[:task_id]
    @cost_line.cost_payment_plan_id = @project.cost_payment_plan.id
    @cost_line.status = 'Pendiente'
    respond_to do |format|
      if @cost_line.save
        format.html { redirect_to project_milestone_task_path(@project, @milestone, @task), notice: 'Cost was successfully created.' }
        format.json { render :show, status: :created, location: @cost_line }
      else
        format.html { render :add_cost_line }
        format.json { render json: @cost_line.errors, status: :unprocessable_entity }
      end
    end
  end

  def assign_resource
    ra = ResourceAssignation.new(resource_assignement_params)
    ra.task_id = @task.id
    respond_to do |format|
      if ra.save
        format.html { redirect_to project_milestone_task_path(@project, @milestone, @task), notice: 'Recurso agregado con exito' }
      else
        format.html { redirect_to project_milestone_task_path(@project, @milestone, @task), notice: 'Ha ocurrido un problema' }
      end
    end
  end

  #### ----------- Private methods ----------- ####

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_task
    @task = Task.find(params[:id])
  end

  def set_milestone
    @milestone = Milestone.find(params[:milestone_id])
  end

  def set_project
    @project = Project.find(params[:project_id])
  end

  def set_admin
    @admin = current_project_manager.has_role? :admin
  end

  # Never trust parameters from the scary internet, 
  # only allow the white list through.
  def task_params
    params.require(:task).permit(:name, :description, :min_duration, :most_probable_duration, :max_duration, :pm_duration_estimation, :milestone_id, :fake, :admin_duration_estimation)
  end

  def cost_line_params
    params.require(:cost_line).permit(:name, :description, :amount, :payment_week, :funding_source)
  end

  def resource_assignement_params
    params.permit(:human_resource_id, :time)
  end
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/tasks/_add_tasks_list.html.erb
<% tasks = locals[:tasks] %>
<br>
<p> Aquí puedes seleccionar las tareas que quieras agregar al hito, debes agregar sólo las tareas que encuentres necesarias para el éxito del hito.</p>
<table>
  <thead>
    <tr>
      <th>Nombre</th>
      <th>Descripción</th>
      <th>Min (días) </th>
      <th>Moda (días) </th>
      <th>Max (días)</th>
      <th>Estimación Jefe Proyecto (días)</th>
      <th colspan="3">Agregar? </th>
    </tr>
  </thead>

  <tbody>
    <% tasks.each do |task| %>
      <tr>
        <td><%= task.name %></td>
        <td><%= task.description %></td>
        <td><%= task.min_duration %></td>
        <td><%= task.most_probable_duration %></td>
        <td><%= task.max_duration %></td>
        <td><%= task.pm_duration_estimation %></td>
        <td><%= check_box_tag "task_ids[]", task.id %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= submit_tag 'Agregar tareas', class: "button tiny success" %>

app/views/tasks/_costs_list.html.erb
<% cost_lines = locals[:costs_list] %>


<table>
  <thead>
    <tr>
      <th> Nombre </th>
      <th> Descripcion </th>
      <th> Monto estimado </th>
      <th> Semana de pago estimada </th>
      <th> Monto real </th>
      <th> Semana de pago real</th>
      <th> Fuente de financiamiento</th>
      <th> Estado </th>

      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% cost_lines.each do |cost_line| %>
      <tr>
        <td><%= cost_line.name %></td>
        <td><%= cost_line.description %></td>
        <td><%= cost_line.amount %></td>
        <td><%= cost_line.payment_week %></td>
        <td><%= cost_line.real_amount %></td>
        <td><%= cost_line.real_payment_week %></td>
        <td><%= cost_line.funding_source %></td>
        <td><%= cost_line.status %></td>
        <td><%= link_to 'Declarar pago', set_real_cost_path(@project, cost_line), class: 'button tiny warning' unless cost_line.paid? %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/tasks/_form.html.erb
<% task = locals[:task] %>
<% milestone = locals[:milestone] %>
<% project = locals[:project] %>
<% f = locals[:form] %>
  <% if task.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(task.errors.count, "error") %> prohibited this task from being saved:</h2>

      <ul>
      <% task.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :min_duration %><br>
    <%= f.number_field :min_duration %>
  </div>
  <div class="field">
    <%= f.label :most_probable_duration %><br>
    <%= f.number_field :most_probable_duration %>
  </div>
  <div class="field">
    <%= f.label :max_duration %><br>
    <%= f.number_field :max_duration %>
  </div>
  <div class="field">
    <%= f.label :admin_duration_estimation %><br>
    <%= f.number_field :admin_duration_estimation %>
  </div>
  <div class="field">
    <%= f.label :fake %><br>
    <%= f.check_box :fake %>
  </div>
  <!-- Uncomment this in case you want to explicitly select the milestone
  <div class="field">
    <%= #f.select(:milestone_id, options_for_select(milestones, nil)) 
    %>
  </div>
  -->
  <div class="actions">
    <%= f.submit(class: 'button success small') %>
  </div>

app/views/tasks/_task_duration_table.html.erb
<% task = locals[:task] %>

  <table>
    <tr>
      <th>Min</th>
      <th>Más probable</th>
      <th>Max</th>
      <th>Estimada</th>
    </tr>
    <tr>
      <td> <%= @task.min_duration %> </td>
      <td> <%= @task.most_probable_duration %> </td>
      <td> <%= @task.max_duration %> </td>
      <td> <%= @task.pm_duration_estimation %> </td>
    </tr>
  </table>

app/views/tasks/_task_list.html.erb
<% tasks = locals[:tasks]%>
<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <%- if @project.modificable? %>
        <th>Min (días) </th>
        <th>Moda (días) </th>
        <th>Max (días)</th>
      <% end -%>
      <th>Duración estimada (días)</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% tasks.each do |task| %>
      <tr>
        <td><%= task.name %></td>
        <td><%= task.description %></td>
        <%- if @project.modificable? %>
          <td><%= task.min_duration %></td>
          <td><%= task.most_probable_duration %></td>
          <td><%= task.max_duration %></td>
        <% end -%>
        <%- unless @admin %>
          <td><%= task.pm_duration_estimation %></td>
          <td><a href="#" data-reveal-id="estimar-<%= task.id%>" class="radius button tiny secondary">Estimar</a></td>
        <% else %>
          <td><%= task.admin_duration_estimation %></td>
        <% end -%>
        <td><%= link_to 'Ver detalles', project_milestone_task_path({ :project_id => @project.id, :milestone_id => @milestone.id, :id => task.id }), { class: 'button info tiny' }%></td>
        <td><%= link_to 'Eliminar', project_milestone_task_path({ :project_id => @project.id, :milestone_id => @milestone.id, :id => task.id }), class: 'button alert tiny' , method: :delete, data: { confirm: 'Estas seguro que deseas elimienar esta tarea?' } if @project.modificable? %></td>
      </tr>
      <!-- modal -->
      <div id="estimar-<%= task.id%>" class="reveal-modal" data-reveal aria-labelledby="task-<%= task.id%>-title" aria-hidden="true" role="dialog">
        <h2 id="task-<%= task.id%>-title">Estimar duración</h2>
        <%= form_tag estimate_duration_project_milestone_task_path({:project_id => @project.id, :milestone_id => @milestone.id, :id => task.id }) do %>
          <div class="field">
            <%= number_field_tag :pm_duration_estimation %>
          </div>
           <%= submit_tag 'Estimar', { class: 'button success tiny' } %> 
        <% end -%>
        <a class="close-reveal-modal" aria-label="Close">&#215;</a>
      </div>
    <% end %>
  </tbody>
</table>

app/views/tasks/add_cost_line.html.erb
<p>
  <h3> Agregar costo a <%= @task.name %></h3>  
</p>

<%= form_for(@cost_line, url: task_cost_path(@project, @milestone, @task)) do |f| %>
	<% if @cost_line.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(task.errors.count, "error") %> prohibited this cost line from being saved:</h2>

      <ul>
      <% @cost_line.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name, 'Nombre' %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description, 'Descripción' %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field left large-3">
    <%= f.label 'Monto estimado' %><br>
    <%= f.number_field :amount %>
  </div>
  <div class="field left large-1"></div>
  <div class="field left large-3">
    <%= f.label 'Semana de pago estimada' %><br>
    <%= f.number_field :payment_week %>
  </div>
  <div class="field left large-1"></div>
  <div class="field left large-4">
    <%= f.label 'Fuente de financiamiento' %><br>
    <%= f.select(:funding_source, ['Costo de actividades','Reserva de actividades','Reserva de contingencias','Reserva de gestión']) %>
  </div>

   <div class="actions">
    <%= f.submit('Agregar nuevo costo',class: 'button success tiny') %>
    <%= link_to 'Cancelar', project_milestone_task_path({ :project_id => @project.id, :milestone_id => @milestone.id, :id => @task.id }), class: 'button secondary tiny' %>
  </div>
<% end -%>

app/views/tasks/edit.html.erb
<h1>Editing Task</h1>

<%= form_for(@task, url: project_milestone_task_path(@project, @milestone, @task)) do |f| %>
	<%= render 'form' , :locals => { form: f, milestone: @milestone, project: @project, task: @task } %>
<% end -%>
<%= link_to 'Show', project_milestone_task_path(@project, @milestone, @task) %> |
<%= link_to 'Back', project_milestone_path(@project, @milestone) %>

app/views/tasks/index.html.erb
<h1><%= @milestone.name%></h1>
<h3>Lista de tareas</h3>
<%= render 'task_list', :locals => { tasks: @tasks } %>

<br>

<%= link_to 'New Task', new_project_milestone_task_path %>

app/views/tasks/new.html.erb
<h1>New Task</h1>

<%= form_for(@task, url: project_milestone_tasks_path(@project, @milestone)) do |f| %>
	<%= render 'form', :locals => { form: f, milestone: @milestone, project: @project, task: @task } %>
<% end -%>
<%= link_to 'Back', project_milestone_path(@project, @milestone) %>

app/views/tasks/show.html.erb
<div class="row">
  <p></p>
  <%= link_to 'Volver a hito', project_milestone_path(@project, @milestone), class: 'button tiny secondary' %>
</div>
<p>
  <h3><%= @task.name %></h3>
</p>

<p>
  <strong>Description:</strong>
  <%= @task.description %>
</p>

<p>
  <h4>Duración</h4>
  <%= render 'task_duration_table', locals: { task: @task} %>
</p>
<p>
  <h4> Costos asociados </h4>
  <%= link_to 'Nuevo costo', new_task_cost_path({ :project_id => @project.id, :milestone_id => @milestone.id, :task_id => @task.id }), class:'button tiny success' if @admin %>
  <%= render 'costs_list', locals: { costs_list: @costs_list} %>
</p>
<p>
<% unless @admin %>
  <h4>Recursos humanos</h4>
  <!-- Crear nueva asignación-->
  <div class="panel">
    <h6>Asignar recurso</h6>
    <%= form_tag assign_resource_path %>
    <div class="field">
      <%= label_tag :human_resource_id, 'Recurso humano' %>
      <%= select_tag(:human_resource_id, options_for_select(@hhrr_array)) %>
    </div>
    <div class="field">
      <%= label_tag :time, 'Tiempo (días)' %>
      <%= number_field_tag :time %>
    </div>
    <%= submit_tag 'Asignar', class: 'button tiny success' %>

    <table>
      <caption>Recursos asignados</caption>
      <thead>
        <th>Recurso</th>
        <th>Tiempo</th>
      </thead>
      <tbody>
        <% @hhrr_assigned.each do |hr| %>
        <tr>
          <td><%= HumanResource.find(hr.human_resource_id).name %></td>
          <td><%= hr.time %></td>
        </tr>
        <% end -%>
      </tbody>
    </table>
  </div>
  <% end -%>
</p>