config/routes.rb
Rails.application.routes.draw do
  resources :human_resources
  devise_for :project_managers
  resources :cost_payment_plans
  resources :projects do
    resources :milestones do
      resources :tasks do
        member do
          post 'estimate_duration'
        end
      end
    end
    resources :stakeholders do
      member do
        put 'increase_commitment'
      end
    end
    member do
      post 'create_requirement' # create_requirement_project_path (projects#create_requirement)
      post 'configure_simulator' 
      put 'edit_budget'  # /projects/:id/edit_budget
      get 'execute_step'
      post 'negotiate'
    end
  end

    get 'projects/:id/costs', to: 'projects#costs', as: 'project_costs'
    get 'projects/:project_id/milestones/:milestone_id/tasks/:task_id/add_cost_line', to: 'tasks#add_cost_line', as: 'new_task_cost'
    post 'projects/:project_id/milestones/:milestone_id/tasks/:task_id/add_cost_line', to: 'tasks#create_cost_line', as: 'task_cost'
    get 'projects/:project_id/pay_cost/:cost_line_id', to: 'projects#insert_real_cost', as: 'set_real_cost'
    post 'projects/:project_id/pay_cost/:cost_line_id', to: 'projects#save_real_cost', as: 'pay_cost'

    post 'projects/:id/clone', to: 'projects#clone', as: 'clone_project'
    post 'projects/:project_id/milestones/clone', to: 'milestones#clone', as: 'clone_milestones'
    post 'projects/:project_id/milestones/:id/tasks/clone', to: 'tasks#clone', as: 'clone_tasks'

    get 'projects/:project_id/precedents', to: 'milestones#precedent_index', as: 'precedents'
    post 'projects/:project_id/precedents', to: 'milestones#create_precedent', as: 'create_precedents'
    get 'projects/:project_id/precedents/new', to: 'milestones#new_precedent', as: 'new_precedents'
    
    get '/', to: 'projects#scope_statement', as: 'scope_statement'

    get 'human_resources_shop', to: 'human_resources#shop', as: 'human_resources_shop'
    post 'human_resources/:id/clone', to: 'human_resources#clone', as: 'human_resources_clone'

    post 'projects/:project_id/milestones/:milestone_id/tasks/:id/assign_resource', to: 'tasks#assign_resource', as: 'assign_resource'

    put 'projects/:project_id/edit_requirement/:id', to: 'projects#edit_requirement', as: 'edit_requirement'

  root 'projects#scope_statement'

end

app/models/stakeholder.rb
# == Schema Information
#
# Table name: stakeholders
#
#  id                   :integer          not null, primary key
#  name                 :string
#  commitment_level     :integer
#  influence            :integer
#  power                :integer
#  created_at           :datetime         not null
#  updated_at           :datetime         not null
#  project_id           :integer
#  is_admin_stakeholder :boolean
#

class Stakeholder < ActiveRecord::Base
  belongs_to :project

  def increase_commitment
    if self.commitment_level < 5
      self.commitment_level += 1
      if save
        true
      else
        false
      end
    else
      false
    end
  end
end

app/controllers/stakeholders_controller.rb
class StakeholdersController < ApplicationController
  before_action :set_stakeholder, only: [:show, :edit, :update, :destroy, :increase_commitment]
  before_action :set_project, :set_admin
  before_action :authenticate_project_manager!
  # GET projects/1/stakeholders
  # GET projects/1/stakeholders.json
  def index
    @stakeholders = @project.stakeholders
  end

  # GET projects/1/stakeholders/1
  # GET projects/1/stakeholders/1.json
  def show
  end

  # GET projects/1/stakeholders/new
  def new
    @stakeholder = Stakeholder.new
  end

  # GET projects/1/stakeholders/1/edit
  def edit
  end

  # POST projects/1/stakeholders
  # POST projects/1/stakeholders.json
  def create
    @stakeholder = Stakeholder.new(stakeholder_params)
    @stakeholder.project_id = @project.id
    @stakeholder.is_admin_stakeholder = @admin
    respond_to do |format|
      if @stakeholder.save
        format.html { redirect_to project_stakeholders_path(@project), notice: 'Stakeholder was successfully created.' }
        format.json { render :show, status: :created, location: @stakeholder }
      else
        format.html { render :new }
        format.json { render json: @stakeholder.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT projects/1/stakeholders/1
  # PATCH/PUT projects/1/stakeholders/1.json
  def update
    respond_to do |format|
      if @stakeholder.update(stakeholder_params)
        format.html { redirect_to project_stakeholder_path(@project, @stakeholder), notice: 'Stakeholder was successfully updated.' }
        format.json { render :show, status: :ok, location: @stakeholder }
      else
        format.html { render :edit }
        format.json { render json: @stakeholder.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT projects/1/stakeholders/1/increase_commitment
  def increase_commitment
    respond_to do |format|
      if @stakeholder.increase_commitment
        format.html { redirect_to project_stakeholders_path(@project), notice: 'Nivel de compromiso aumentado'}
      else
        format.html { redirect_to project_stakeholders_path(@project), notice: 'No se pudo incrementar el nivel de compromiso' }
      end
    end
  end


  # DELETE projects/1/stakeholders/1
  # DELETE projects/1/stakeholders/1.json
  def destroy
    @stakeholder.destroy
    respond_to do |format|
      format.html { redirect_to project_stakeholders_url, notice: 'Stakeholder was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_stakeholder
      @stakeholder = Stakeholder.find(params[:id])
    end

    def set_project
      @project = Project.find(params[:project_id])
    end

    def set_admin
      if current_project_manager
        @admin = current_project_manager.has_role? :admin
      else
        @admin = false
      end
    end
    # Never trust parameters from the scary internet, only allow the white list through.
    def stakeholder_params
      params.require(:stakeholder).permit(:name, :commitment_level, :influence, :power)
    end
end

app/helpers/stakeholders_helper.rb
module StakeholdersHelper
end

app/views/stakeholders/_form.html.erb
<%= form_for(@stakeholder, url: project_stakeholders_path(@project)) do |f| %>
  <% if @stakeholder.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@stakeholder.errors.count, "error") %> prohibited this stakeholder from being saved:</h2>

      <ul>
      <% @stakeholder.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name, 'Nombre' %><br>
    <%= f.text_field :name, required: :true %>
  </div>
  <div class="field large-4 left">
    <%= f.label :commitment_level, 'Nivel de compromiso' %><br>
    <%= f.number_field :commitment_level, required: :true %>
  </div>
  <div class="field large-1 left"></div>
  <div class="field large-3 left">
    <%= f.label :influence, 'Influencia' %><br>
    <%= f.number_field :influence, required: :true %>
  </div>
  <div class="field large-1 left"></div>
  <div class="field large-3 left">
    <%= f.label :power, 'Poder' %><br>
    <%= f.number_field :power, required: :true %>
  </div>
  <div class="actions">
    <%= f.submit({class: 'button tiny success'}) %>
  </div>
<% end %>

app/views/stakeholders/_stakeholders_list.html.erb
<% stakeholders = locals[:stakeholders] %>
<table>
  <thead>
    <tr>
      <th>Nombre</th>
      <th>Nivel de compromiso</th>
      <th>Influencia</th>
      <th>Poder</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>

    <%- if stakeholders then %>
      <% stakeholders.each do |stakeholder| %>
      <tr>
         <td><%= stakeholder.name %></td>
        <td><%= stakeholder.commitment_level %></td>
        <td><%= stakeholder.influence %></td>
        <td><%= stakeholder.power %></td>
        <td><%= link_to 'Aumentar compromiso', increase_commitment_project_stakeholder_path(@project, stakeholder), method: :put, class: 'button info tiny' %></td>
        <td><%= link_to 'Eliminar', project_stakeholder_path(@project, stakeholder), method: :delete, data: { confirm: 'Are you sure?' }, class: 'button tiny alert' if @admin%></td>
      </tr>
      <% end %>
    <% end -%>
  </tbody>
</table>

app/views/stakeholders/edit.html.erb
<h1>Editing Stakeholder</h1>

<%= render 'form' %>

<%= link_to 'Show', @stakeholder %> |
<%= link_to 'Back', stakeholders_path %>

app/views/stakeholders/index.html.erb
<h1>Lista de interesados</h1>

<table>
  <thead>
    <tr>
      <th>Nombre</th>
      <th>Nivel de compromiso</th>
      <th>Influencia</th>
      <th>Poder</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @stakeholders.each do |stakeholder| %>
      <tr>
        <td><%= stakeholder.name %></td>
        <td><%= stakeholder.commitment_level %></td>
        <td><%= stakeholder.influence %></td>
        <td><%= stakeholder.power %></td>
        <td><%= link_to 'Aumentar compromiso', increase_commitment_project_stakeholder_path(@project, stakeholder), method: :put, class: 'button info tiny' %></td>
        <td><%= link_to 'Eliminar', project_stakeholder_path(@project, stakeholder), method: :delete, data: { confirm: 'Are you sure?' }, class: 'button tiny alert' if @admin%></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<%- if @admin %>
  <%= link_to 'Crear nuevo interesado', new_project_stakeholder_path(@project), class: 'button tiny success'  %>
<% end -%>
<%= link_to 'Volver a vista general', project_path(@project), class: 'button tiny secondary' %>

app/views/stakeholders/new.html.erb
<h1>Nuevo interesado</h1>

<%= render 'form' %>

<%= link_to 'Cancelar', project_stakeholders_path, class: 'button tiny secondary' %>

app/views/stakeholders/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @stakeholder.name %>
</p>

<p>
  <strong>Commitment level:</strong>
  <%= @stakeholder.commitment_level %>
</p>

<p>
  <strong>Influence:</strong>
  <%= @stakeholder.influence %>
</p>

<p>
  <strong>Power:</strong>
  <%= @stakeholder.power %>
</p>

<%= link_to 'Edit', edit_stakeholder_path(@stakeholder) %> |
<%= link_to 'Back', stakeholders_path %>