config/routes.rb
Rails.application.routes.draw do
  resources :human_resources
  devise_for :project_managers
  resources :cost_payment_plans
  resources :projects do
    resources :milestones do
      resources :tasks do
        member do
          post 'estimate_duration'
        end
      end
    end
    resources :stakeholders do
      member do
        put 'increase_commitment'
      end
    end
    member do
      post 'create_requirement' # create_requirement_project_path (projects#create_requirement)
      post 'configure_simulator' 
      put 'edit_budget'  # /projects/:id/edit_budget
      get 'execute_step'
      post 'negotiate'
    end
  end

    get 'projects/:id/costs', to: 'projects#costs', as: 'project_costs'
    get 'projects/:project_id/milestones/:milestone_id/tasks/:task_id/add_cost_line', to: 'tasks#add_cost_line', as: 'new_task_cost'
    post 'projects/:project_id/milestones/:milestone_id/tasks/:task_id/add_cost_line', to: 'tasks#create_cost_line', as: 'task_cost'
    get 'projects/:project_id/pay_cost/:cost_line_id', to: 'projects#insert_real_cost', as: 'set_real_cost'
    post 'projects/:project_id/pay_cost/:cost_line_id', to: 'projects#save_real_cost', as: 'pay_cost'

    post 'projects/:id/clone', to: 'projects#clone', as: 'clone_project'
    post 'projects/:project_id/milestones/clone', to: 'milestones#clone', as: 'clone_milestones'
    post 'projects/:project_id/milestones/:id/tasks/clone', to: 'tasks#clone', as: 'clone_tasks'

    get 'projects/:project_id/precedents', to: 'milestones#precedent_index', as: 'precedents'
    post 'projects/:project_id/precedents', to: 'milestones#create_precedent', as: 'create_precedents'
    get 'projects/:project_id/precedents/new', to: 'milestones#new_precedent', as: 'new_precedents'
    
    get '/', to: 'projects#scope_statement', as: 'scope_statement'

    get 'human_resources_shop', to: 'human_resources#shop', as: 'human_resources_shop'
    post 'human_resources/:id/clone', to: 'human_resources#clone', as: 'human_resources_clone'

    post 'projects/:project_id/milestones/:milestone_id/tasks/:id/assign_resource', to: 'tasks#assign_resource', as: 'assign_resource'

    put 'projects/:project_id/edit_requirement/:id', to: 'projects#edit_requirement', as: 'edit_requirement'

  root 'projects#scope_statement'

end

app/models/project.rb
# == Schema Information
#
# Table name: projects
#
#  id                  :integer          not null, primary key
#  name                :string
#  actual_week         :integer
#  created_at          :datetime         not null
#  updated_at          :datetime         not null
#  project_manager_id  :integer
#  status              :string
#  is_admin_project    :boolean
#  start_date          :date
#  strategic_objective :text
#

class Project < ActiveRecord::Base
  has_many :milestones, dependent: :destroy
  has_one :cost_payment_plan, dependent: :destroy
  has_many :stakeholders, dependent: :destroy
  has_one :budget, dependent: :destroy
  has_many :requirements, dependent: :destroy
  has_many :human_resources, dependent: :destroy
  has_one :simulator, dependent: :destroy

  scope :from_admin, -> { where(is_admin_project: true) }
  scope :cloned, -> { where(is_admin_project: false) }

  def modificable?
    return true if (status == 'Inicio')
    false
  end

  def monitorable?
    return true if (status == 'Monitoreo y control')
    false
  end

  def human_resources_for_select
    human_resources.map { |hr| [hr.description, hr.id] }
  end

  # This method returns the duration of the project in days
  def duration
    e_date = start_date
    all_tasks.each do |task|
      e_date = task.end_date if task.end_date > e_date
    end
    (e_date - start_date).to_i
  end

  # This method cares of paying the salaries, it verifies that it hasn't
  # been paid earlier this week.
  # It's funded by the activities reserve
  def pay_salaries(week)
    cpp = cost_payment_plan
    human_resources.each do |hr|
      nyd = 'Pago sueldo ' + hr.name
      am = hr.salary
      unless CostLine.where(name: nyd, payment_week: week).length > 0
        cl = CostLine.new(name: nyd, description: nyd,
                          amount: am, real_amount: am,
                          payment_week: week, real_payment_week: week,
                          cost_payment_plan_id: cpp.id, status: 'Pagado',
                          funding_source: 'Reserva de actividades')
        cl.save
        use_budget(cl)
      end
    end
  end

  # Method used to increase the used amount of the budget
  def use_budget(cost_line)
    bud = budget
    case cost_line.funding_source
    when 'Costo de actividades'
      bud.activities_cost_used += cost_line.real_amount
    when 'Reserva de actividades'
      bud.activities_reserve_used += cost_line.real_amount
    when 'Reserva de contingencias'
      bud.contingency_reserve_used += cost_line.real_amount
    when 'Reserva de gestión'
      bud.managment_reserve_used += cost_line.real_amount
    end
    bud.save 
  end

  # This method return an array of the project tasks with columns
  # [:name, :start_date, :end_date]
  def tasks_for_timeline
    tasks_f_time ||= []
    milestones.each do |mile|
      mile.tasks.each do |task|
        task.update(start_date: start_date) if task.start_date.nil?
        task.update(end_date: task.start_date + task.pm_duration_estimation.days) if task.end_date.nil?
        tasks_f_time << [task.name + ' | ' + mile.name + ' | ' + task.advance_percentage.to_s + "% ", task.start_date, task.end_date]
      end
    end
    tasks_f_time
  end

  def all_tasks
    tasks ||= []
    milestones.each do |mile|
      mile.tasks.each do |task|
        tasks << task
      end
    end
    tasks
  end

  def active_tasks
    tasks ||= []
    milestones.each do |mile|
      mile.tasks.active.each do |task|
        tasks << task
      end
    end
    tasks
  end

  def waiting_tasks
    tasks ||= []
    milestones.each do |mile|
      mile.tasks.waiting.each do |task|
        tasks << task
      end
    end
    tasks
  end

  def finished_tasks
    tasks ||= []
    milestones.each do |mile|
      mile.tasks.finished.each do |task|
        tasks << task
      end
    end
    tasks
  end

  # Clone all the elements and params of the original project to
  # the new one
  def clone_characteristics_from(original_project, current_project_manager)
    # Create a new cost payment plan for this project
    cpp = CostPaymentPlan.create!
    self.cost_payment_plan = cpp
    clone_budget_from(original_project)
    clone_requirements_from(original_project)
    clone_stakeholders_from(original_project)
    self.simulator = original_project.simulator.clone
    self.project_manager_id = current_project_manager.id
    self.is_admin_project = current_project_manager.has_role? :admin
    self.status = 'Inicio'
    save
  end

  def clone_budget_from(original_project)
    self.budget = original_project.budget.dup
    save
  end

  # Clone the requirements of the project
  def clone_requirements_from(original_project)
    original_project.requirements.each do |req|
      r2 = req.dup
      r2.attributes = { project_id: id }
      r2.save
    end
  end

  # Clone the stakeholders
  def clone_stakeholders_from(original_project)
    original_project.stakeholders.each do |stakeholder|
      sh2 = stakeholder.dup
      sh2.attributes =  { project_id: id, is_admin_stakeholder: false }
      sh2.save
    end
  end

  # ---- Methods for simulation ---- #

  # To win the game the project must be completed,
  # in order to do that all the milestones should be finished
  def win?
    milestones.each do |mile|
      return false unless mile.status == 'Aprobado'
    end
    true
  end

  # To loose the game 1 of 3 conditions mus occur:
  # => Project expenses consume the profit of the project
  # => Cost for the client increases in 25%
  # => There is a delay of more than 25%
  def loose?
    return true if budget.actual_earnings < 0
    return true if simulator.initial_budget and budget.total_used > 1.25 * simulator.initial_budget
    return true if simulator.actual_duration and simulator.actual_duration > 1.25 * simulator.original_duration
    return true if simulator.day and simulator.day > simulator.actual_duration
    false
  end

  # This method is for restarting thr project
  def restart
    budget.restart
    cost_payment_plan.restart
    self.update(actual_week: 0, status: 'Inicio')
    milestones.map { |mile| mile.restart }
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: [:show, :edit, :update, :destroy, :costs, :create_requirement, :edit_budget, :configure_simulator, :execute_step]
  before_action :set_admin
  before_action :authenticate_project_manager!
  # GET /projects
  # GET /projects.json
  def index
    if @admin
      @projects = Project.from_admin
      @cloned_projects = Project.cloned
    else
      @projects = current_project_manager.projects
      @admin_projects = Project.from_admin
    end
  end

  # GET /projects/1
  # GET /projects/1.json
  def show
    @cost_payment_plan = @project.cost_payment_plan
    @cost_lines = @cost_payment_plan.cost_lines
    sum = 0
    @estimated_payment_schedule = @cost_payment_plan.estimated_payment_schedule(@project).sort{|x,y| x[0] <=> y[0]}.map { |x,y| { x => (sum += y)} }.reduce({}, :merge)
    sum = 0
    @real_payment_schedule = @cost_payment_plan.real_payment_schedule(@project).sort{|x,y| x[0] <=> y[0]}.map { |x,y| { x => (sum += y)} }.reduce({}, :merge)
    @stakeholders = @project.stakeholders
    @milestones = @project.milestones
    @budget = @project.budget
    @budget_data = @budget.data_for_stacked_column
    if @project.simulator.nil?
      @project.simulator = Simulator.create!
      @project.save
    end
    @simulator = @project.simulator
    @can_start_simulation = @simulator.can_start?
    @tasks_timeline_data = @project.tasks_for_timeline if not @admin and @can_start_simulation
  end

  def clone
    original_project = Project.find(params[:id])
    @project = original_project.dup
    @project.save
    @project.clone_characteristics_from(original_project, current_project_manager)
    respond_to do |format|
      if @project.save
        format.html { redirect_to @project, notice: 'Project was successfully created.' }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # GET /projects/new
  def new
    @project = Project.new
  end

  # GET /projects/1/edit
  def edit
  end

   # POST /projects
  # POST /projects.json
  def create
    @project = Project.new(project_params)
    cpp = CostPaymentPlan.create!
    budget = Budget.create!
    simulator = Simulator.create!
    @project.cost_payment_plan = cpp
    @project.budget = budget
    @project.simulator = simulator
    @project.project_manager_id = current_project_manager.id
    @project.is_admin_project = current_project_manager.has_role? :admin
    @project.status = 'Inicio'
    respond_to do |format|
      if @project.save
        format.html { redirect_to @project, notice: 'Project was successfully created.' }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1
  # PATCH/PUT /projects/1.json
  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to @project, notice: 'Project was successfully updated.' }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    @project.destroy
    respond_to do |format|
      format.html { redirect_to projects_url, notice: 'Project was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  # ---- Costs ---- #

  def edit_budget
    b = @project.budget
    b.update(budget_params)
    b.profit = ((b.activities_cost + b.activities_reserve + b.contingency_reserve + b.managment_reserve) * 0.2).to_i
    respond_to do |format|
      if b.save
        format.html { redirect_to @project, notice: 'Presupuesto actualizado' }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { redirect_to @project, notice: 'Ocurrio un problema al cambiar el presupuesto' }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end

  end

   # GET /projects/1/costs (show project costs)
  def costs
    @cost_payment_plan = @project.cost_payment_plan
    @budget = @project.budget
  end

  def insert_real_cost
    @cost_line = CostLine.find(params[:cost_line_id])
  end

  def save_real_cost
    @project = Project.find(params[:project_id])
    @cost_line = CostLine.find(params[:cost_line_id])
    respond_to do |format|
      if @cost_line.pay( params[:real_amount], params[:real_payment_week])
        format.html { redirect_to project_costs_path(@project), notice: 'Costo pagado satisfactoriamente' }
      else
        format.html { redirect_to insert_real_cost_path(@project), notice: 'Something interrupted the operation, please try again'}
      end
    end
  end

  # ---- SCOPE STATEMENT ---- #

  # GET /
  # We select the project of the project type assigned to this manager
  # In case he don't have one assigned we set this as the first admin project.

  def scope_statement
    unless @admin
      if current_project_manager.projects.first.nil?
        project_id = current_project_manager.project_type_id
      else
        project_id = current_project_manager.projects.first.id
      end
      if ( project_id == 0 or project_id == nil)
        if ( Project.from_admin.first != nil)
          current_project_manager.project_type_id = Project.from_admin.first.id
          project_id = current_project_manager.project_type_id
        else
          respond_to do |format|
            format.html { redirect_to projects_path }
          end
          return
        end
      end
      @project = Project.find(project_id)
    else
      respond_to do |format|
        format.html { redirect_to projects_path }
      end
    end
  end

  # ---- Requirements ---- #

  def create_requirement
    req = Requirement.new(requirement_params)
    req.project_id = params[:id]
    respond_to do |format|
      if req.save
        format.html { redirect_to project_path(@project), notice: 'Requisito agregado correctamente' }
      else
        format.html { redirect_to project_path(@project), notice: 'Ocurrió un problema al tratar de guardar el requisito' }
      end
    end
  end

  def edit_requirement
    @project = Project.find(params[:project_id])
    req = Requirement.find(params[:id])
    respond_to do |format|
      if req.update(requirement_params)
        format.html { redirect_to project_path(@project), notice: 'Requisito agregado correctamente' }
      else
        format.html { redirect_to project_path(@project), notice: 'Ocurrió un problema al tratar de guardar el requisito' }
      end
    end
  end

  # ---- SIMULATOR ---- #
  def configure_simulator
    respond_to do |format|
      if @project.simulator.update(simulator_params)
        format.html { redirect_to project_path(@project), notice: 'Requisito agregado correctamente' }
      else
        format.html { redirect_to project_path(@project), notice: 'Ocurrió un problema al tratar de guardar el requisito' }
      end
    end
  end

  def execute_step
    @project.simulator.execute_step
    respond_to do |format|
      format.html { redirect_to project_path(@project), notice: 'Etapa simuada' }
    end
  end

  def negotiate
    set_project
    notice = @project.simulator.negotiate(params[:type], { amount: params[:amount], days: params[:days],
                                  add_requirement_id: params[:add_requirement_id],
                                  delete_requirement_id: params[:delete_requirement_id] })
    respond_to do |format|
      format.html { redirect_to project_path(@project), notice: notice }
    end

  end

  private

    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end

    def set_admin
      if current_project_manager
        @admin = current_project_manager.has_role? :admin
      else
        @admin = false
      end
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def project_params
      params.require(:project).permit(:name, :actual_week, :start_date, :strategic_objective)
    end

    def requirement_params
      params.permit(:requirement_id, :name, :description, :is_present)
    end

    def budget_params
      params.permit(:activities_cost, :activities_reserve, :contingency_reserve, :managment_reserve)
    end

    def simulator_params
      params.permit(:risk_activation_prob, :resource_unavailable_prob, :scope_modify_prob, :plan_change_prob, :step_length)
    end

end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_admin_simulator_bar.html.erb
<a href="#" data-reveal-id="configure-simulator" class="radius button tiny info">Configurar simulador</a>
<!-- MODAL CONFIGURE SIMULATOR-->
<div id="configure-simulator" class="reveal-modal" data-reveal aria-labelledby="config-sim-label-title" aria-hidden="true" role="dialog">
  <h2 id="config-sim-label-title">Configurar parametros simulador</h2>
  <p>Recuerde que las probabilidades son valores entre 0 y 1</p>
  <%= form_for(@simulator, url: configure_simulator_project_path,method: :post, id: 'configure_simulator') do %>
    <div class="field left large-3">
      <%= label_tag  :risk_activation_prob, 'Prob. de ocurrencia de riesgo' %>
      <%= number_field_tag :risk_activation_prob, @simulator.risk_activation_prob, min: 0, max: 1, step: 'any' %>
    </div>
    <div class="field left large-1"></div>
    <div class="field left large-3">
      <%= label_tag  :resource_unavailable_prob, 'Prob. rec. humano no disponible' %>
      <%= number_field_tag :resource_unavailable_prob, @simulator.resource_unavailable_prob, min: 0, max: 1, step: 'any' %>
    </div>
    <div class="field left large-1"></div>
    <div class="field left large-3">
      <%= label_tag  :scope_modify_prob, 'Prob. de cambio de alcance' %>
      <%= number_field_tag :scope_modify_prob, @simulator.scope_modify_prob, min: 0, max: 1, step: 'any' %>
    </div>
    <div class="field left large-1"></div>
    <div class="field left large-3">
      <%= label_tag  :plan_change_prob, 'Prob. de modificacion en las tareas' %>
      <%= number_field_tag :plan_change_prob, @simulator.plan_change_prob, min: 0, max: 1, step: 'any' %>
    </div>
    <div class="field left large-1"></div>
    <div class="field left large-3">
      <%= label_tag  :step_length, 'Días de cada iteración' %>
      <%= number_field_tag :step_length, @simulator.step_length, min: 1 %>
    </div>
    <div class="field left large-5"></div>
    <div class="field left large-4 large-offset-1">
     <%= submit_tag 'Listo', class: 'button success small'  %> 
    </div>
  <a class="close-reveal-modal" aria-label="Close">&#215;</a>
  <% end -%>
</div>

app/views/projects/_costs_panel.html.erb
<% estimated_payment_schedule = locals[:estimated_ps] %>
<% real_payment_schedule = locals[:real_ps] %>
<% budget_data = locals[:budget_data] %>
<div class="large-12" id="costs">
  <div class="row">
    <div class="large-4 left">
      <h3> Evolución de costos </h3>
    </div>
    <div class="large-8 left">
      <%= link_to 'Administrar costos', project_costs_path(@project), class: 'button tiny info ' %>
    </div>
  </div>

  <div class="large-7 left" id="cost_evolution">
    <% sum = 0 %>
    <%= line_chart [{ name: "Costo Estimado", data: estimated_payment_schedule }, { name: "Costo Real", data: real_payment_schedule }] %>
  </div>
  <div class="large-4 right" id="indicators">
  <%= column_chart budget_data, stacked: true%>
  </div>

 </div>

app/views/projects/_create_requirement.html.erb
<%= form_tag create_requirement_project_path, id: 'create_requirement' do %>
  <h5>Crear nuevo requisito</h5>
  <div class="field left large-4">
    <%= label_tag :requirement_id, 'Identificador' %>
    <%= text_field_tag :requirement_id %>
  </div>
  <div class="field left large-1"></div>
  <div class="field left large-4">
    <%= label_tag :name, 'Nombre' %>
    <%= text_field_tag :name %>
  </div>
  <div class="field left large-1"></div>
  <div class="field left large-2">
    <%= label_tag :is_present, 'Es requisito inicial?' %>
    <%= check_box_tag :is_present %>
  </div>
  <div class="field left large-12">
    <%= label_tag :description, 'Descripción' %>
    <%= text_area_tag :description %>
  </div>
  <div class="large-3">
    <%= submit_tag 'Agregar requisito', class: 'button tiny success' %>
  </div>
  <% end -%>

app/views/projects/_define_budget_form.html.erb
<div id="define-budget" class="reveal-modal" data-reveal aria-labelledby="budget-label-title" aria-hidden="true" role="dialog">
  <h2 id="budget-label-title">Definir presupuesto</h2>
  <%= form_for(@budget, url: edit_budget_project_path, method: :put, id: 'define_budget') do %>
    <div class="field left large-2">
      <%= label_tag  :activities_cost, 'Costo de actividades' %>
      <%= number_field_tag :activities_cost, @budget.activities_cost %>
    </div>
    <div class="field left large-1"></div>
    <div class="field left large-2">
      <%= label_tag  :activities_reserve, 'Reserva de actividades' %>
      <%= number_field_tag :activities_reserve, @budget.activities_reserve %>
    </div>
    <div class="field left large-1"></div>
    <div class="field left large-2">
      <%= label_tag  :contingency_reserve, 'Reserva de contingencia' %>
      <%= number_field_tag :contingency_reserve, @budget.contingency_reserve %>
    </div>
    <div class="field left large-1"></div>
    <div class="field left large-2">
      <%= label_tag  :managment_reserve, 'Reserva de gestión' %>
      <%= number_field_tag :managment_reserve, @budget.managment_reserve %>
    </div>
    <div class="field left large-1"></div>
    <div class="field left large-3">
     <%= submit_tag 'Definir', class: 'button success tiny'  %> 
    </div>
  <a class="close-reveal-modal" aria-label="Close">&#215;</a>
  <% end -%>
</div>

app/views/projects/_edit_requirement.html.erb
<% requi = locals[:requirement] %>
<!-- modal -->
<div id="editar-<%= requi.id%>" class="reveal-modal" data-reveal aria-labelledby="req-<%= requi.id%>-title" aria-hidden="true" role="dialog">
  <h2 id="req-<%= requi.id%>-title">Editar nuevo requisito</h2>
  <%= form_tag edit_requirement_path(@project, requi), method: :put, id: "edit_requirement_#{requi.id}" do %>
    <div class="field left large-4">
      <%= label_tag :requirement_id, 'Identificador' %>
      <%= text_field_tag :requirement_id, requi.requirement_id %>
    </div>
    <div class="field left large-1"></div>
    <div class="field left large-4">
      <%= label_tag :name, 'Nombre' %>
      <%= text_field_tag :name, requi.name %>
    </div>
    <div class="field left large-1"></div>
    <div class="field left large-2">
      <%= label_tag :is_present, 'Es requisito inicial?' %>
      <%= hidden_field_tag :is_present, false %>
      <%= check_box_tag :is_present, nil, requi.is_present %>
    </div>
    <div class="field left large-12">
      <%= label_tag :description, 'Descripción' %>
      <%= text_area_tag :description, requi.description %>
    </div>
    <div class="large-3">
      <%= submit_tag 'Actualizar requisito', class: 'button tiny success' %>
    </div>
  <% end -%>
  <a class="close-reveal-modal" aria-label="Close">&#215;</a>
</div>

app/views/projects/_form.html.erb
<%= form_for(@project) do |f| %>
  <% if @project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
      <% @project.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :actual_week %><br>
    <%= f.number_field :actual_week %>
  </div>
  <div class="field">
    <%= f.label :start_date %><br>
    <%= f.date_select :start_date %>
  </div>
  <div class="field">
    <%= f.label :strategic_objective, 'Objetivos estratégicos' %><br>
    <%= f.text_area :strategic_objective %>
  </div>
  <div class="actions">
    <%= f.submit(class: 'button success small') %>
  </div>
<% end %>

app/views/projects/_stakeholders_panel.html.erb
<div class="large-8 left"><h3> Interesados</h3></div>
<div class="large-4 left">
	<%= link_to 'Ver interesados', project_stakeholders_path(@project), class: 'button info tiny'%>
</div>
<div class="row">
  <%= scatter_chart @stakeholders.pluck(:influence,:power), library: { xAxis: { min: 0, max: 5}},ytitle: 'Poder', xtitle: 'Influencia', min: 0, max: 5 %>
</div>
<br><br>

app/views/projects/costs.html.erb
<h1>Plan de pago</h1>
  <%= link_to 'Atrás', project_path(@project), class: 'button secondary tiny' %>
<table>
  <thead>
    <tr>
      <th> Nombre </th>
      <th> Descripcion </th>
      <th> Monto estimado </th>
      <th> Semana de pago estimada </th>
      <th> Monto real </th>
      <th> Semana de pago real</th>
      <th> Fuente de financiamiento</th>
      <th> Estado </th>

      <th colspan="3">Acciones</th>
    </tr>
  </thead>

  <tbody>
    <% @cost_payment_plan.cost_lines.each do |cost_line| %>
      <tr>
        <td><%= cost_line.name %></td>
        <td><%= cost_line.description %></td>
        <td><%= cost_line.amount %></td>
        <td><%= cost_line.payment_week %></td>
        <td><%= cost_line.real_amount %></td>
        <td><%= cost_line.real_payment_week %></td>
        <td><%= cost_line.funding_source %></td>
        <td><%= cost_line.status %></td>
        <td><%= link_to 'Declarar pago', set_real_cost_path(@project, cost_line), class: 'button tiny warning' unless cost_line.paid? %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/projects/edit.html.erb
<h1>Editar proyecto</h1>
<%= link_to 'Volver a dashboard', @project, class: 'button tiny secondary' %>
<%= render 'form' %>

app/views/projects/index.html.erb
<!-- In case the project manager has already selected a project we list the project,
	 on the other hand he/she can pick a project from the admin and duplicate it -->
<%- if ( @projects.length > 0 or @admin ) %>
  <%= render 'your_projects', locals: { projects: @projects, title: 'Tus proyectos' } %>
<% else %>
  <%= render 'add_new_project', locals: { admin_projects: @admin_projects } %>
<% end -%>

<br>
<%- if @admin %>
  <%= render 'your_projects', locals: { projects: @cloned_projects, title: 'Proyectos clonados'} %>
  <%= link_to 'Nuevo proyecto de administrador', new_project_path, class: 'button tiny success' %>
<% end -%>

app/views/projects/insert_real_cost.html.erb
<p>
	<h4>Ingrese el monto real y la semana de pago real</h3>
</p>
<%= form_tag pay_cost_path %>
 	<div class="field">
    <%= label_tag :real_amount, 'Monto real' %><br>
    <%= number_field_tag :real_amount %>
  </div>
  <div class="field">
    <%= label_tag :real_payment_week, 'Semana de pago real' %><br>
    <%= number_field_tag :real_payment_week %>
  </div>
<%= submit_tag "Pagar", class: "button tiny warning" %>

app/views/projects/new.html.erb
<h1>New Project</h1>

<%= render 'form' %>

<%= link_to 'Back', projects_path %>